apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Tempo
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-micro-service
    access: proxy
    orgId: 1
    url: http://host.docker.internal:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo-micro-service
  - name: Tempo
    type: tempo
    uid: tempo-micro-service
    access: proxy
    orgId: 1
    url: http://tempo:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki-micro-service'
        tags: [ 'instance', 'pod', 'namespace', 'hostname' ]
        mappedTags: [ { key: 'org' }, { key: 'service.name', value: 'application' }  ]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true
      serviceMap:
        datasourceUid: 'prometheus-micro-service'
      search:
        hide: false
      nodeGraph:
        enabled: true
  - name: Loki
    type: loki
    uid: loki-micro-service
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo-micro-service
          matcherRegex: \[.+,(.+?),
          name: TraceID
          url: $${__value.raw}