global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'api-gateway'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8765' ]
  - job_name: 'catalog-service'
    scrape_interval: 2s
    metrics_path: '/catalog-service/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8765' ]