version: '3.8'
services:

  order-service:
    build: ..
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - postgresqldb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/appdb
      - SPRING_DATASOURCE_USERNAME=siva
      - SPRING_DATASOURCE_PASSWORD=secret
