name: config-server

on:
  pull_request:
    paths:
      - "config-server/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config-server
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 19
          distribution: "zulu"
          cache: "maven"

      - name: Build and analyze
        run: ./mvnw clean verify
